name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크 아웃
        uses: actions/checkout@v3

      - name: Docker 이미지 빌드
        run: docker build -t adieu0115/myapp:latest

      - name: Docker Hub 로그인
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Docker 이미지 Push
        run: |
          docker tag adieu0115/myapp:latest adieu0115/myapp:latest
          docker push adieu0115/myapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: EC2 서버에 배포
        uses: appleboy/ssh-action@v0.1.16
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            docker pull adieu0115/myapp:latest
            docker stop my-app-container || true
            docker rm my-app-container || true
            docker run -d --name my-app-container -p 8080:8080 adieu0115/myapp:latest